services:
  - type: web
    name: autood
    runtime: python
    buildCommand: |
      npm install --prefix Frontend
      npm run build --prefix Frontend
      mkdir -p backend/dist
      rm -rf backend/dist/*
      cp -r Frontend/dist/. backend/dist/
      pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.0.0
